#!/usr/bin/bash
# 
# Copyright (c) alphaOS
# Written by simargl <archpup-at-gmail-dot-com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

tint2_restart_function() {
  if [ "$(pidof tint2)" ]; then
    killall tint2 && sleep 1s && tint2 &
    exit 0
  else
    tint2 &
    exit 0
  fi
}

conky_restart_function() {
  if [ "$(pidof conky)" ]; then
    killall conky && sleep 1s && conky &
    exit 0
  else
    conky &
    exit 0
  fi
}

# tint2
case "$1" in
  tint2)
  case "$2" in
    restart)
      tint2_restart_function;; 
    theme)
      ln -sf /usr/share/tint2/tint2rc_"$3" $HOME/.config/tint2/tint2rc
      tint2_restart_function;; 
  esac
esac

# conky
case "$1" in
  conky)
  case "$2" in
    restart)
      conky_restart_function;;
    theme)
      ln -sf /usr/share/conky/conky_"$3" $HOME/.conkyrc
      conky_restart_function;;
    esac
  esac
esac

exit