#!/usr/bin/bash
#
# Copyright (c) alphaOS
# Written by simargl <archpup-at-gmail-dot-com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. /etc/rc.conf

# SYSTEM ENVIRONMENT VARIABLES

export TZ=:/etc/localtime
export PS1='[\u@\h \W]\$ '
export HOSTNAME=$(cat /etc/hostname)
export XDG_MENU_PREFIX="lxde-"
export SHELL="/usr/bin/bash"
export EDITOR="emendo"
export BROWSER="web-browser"

for i in LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES \
  LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL; do 
  export "$i"="$LOCALE"
done

for profile in /etc/profile.d/*.sh; do test -r "$profile" && . "$profile"; done
unset profile

if [ $X_AUTOLOGIN == "yes" ]; then exec alphaosx; fi
